remote_theme: techie-joe/mallet

title: gysbfff 的技术博客
description: 关注：网络安全、学习记录、技术实践

author:
  name: gysbfff

hero:
  title: gysbfff 的技术博客
  subtitle: 关注：网络安全、学习记录、技术实践
  background_color: "#888888"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
